# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tool_service_pb2 as tool__service__pb2  # noqa: F401 — relative import patched below

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tool_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolServiceStub(object):
    """────────────────────────────────────────────────────────────────
    Service
    ────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/sf.tools.v1.ToolService/Execute',
                request_serializer=tool__service__pb2.ToolRequest.SerializeToString,
                response_deserializer=tool__service__pb2.ToolResponse.FromString,
                _registered_method=True)
        self.ExecuteStream = channel.unary_stream(
                '/sf.tools.v1.ToolService/ExecuteStream',
                request_serializer=tool__service__pb2.ToolRequest.SerializeToString,
                response_deserializer=tool__service__pb2.ToolChunk.FromString,
                _registered_method=True)
        self.GetSchemas = channel.unary_unary(
                '/sf.tools.v1.ToolService/GetSchemas',
                request_serializer=tool__service__pb2.GetSchemasRequest.SerializeToString,
                response_deserializer=tool__service__pb2.GetSchemasResponse.FromString,
                _registered_method=True)


class ToolServiceServicer(object):
    """────────────────────────────────────────────────────────────────
    Service
    ────────────────────────────────────────────────────────────────

    """

    def Execute(self, request, context):
        """Execute a single tool call; returns when complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStream(self, request, context):
        """Execute and stream output chunks (for long-running tools: build, test, deploy).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchemas(self, request, context):
        """Return OpenAI-compatible schemas for available tools.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=tool__service__pb2.ToolRequest.FromString,
                    response_serializer=tool__service__pb2.ToolResponse.SerializeToString,
            ),
            'ExecuteStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteStream,
                    request_deserializer=tool__service__pb2.ToolRequest.FromString,
                    response_serializer=tool__service__pb2.ToolChunk.SerializeToString,
            ),
            'GetSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchemas,
                    request_deserializer=tool__service__pb2.GetSchemasRequest.FromString,
                    response_serializer=tool__service__pb2.GetSchemasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sf.tools.v1.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sf.tools.v1.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """────────────────────────────────────────────────────────────────
    Service
    ────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.tools.v1.ToolService/Execute',
            tool__service__pb2.ToolRequest.SerializeToString,
            tool__service__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sf.tools.v1.ToolService/ExecuteStream',
            tool__service__pb2.ToolRequest.SerializeToString,
            tool__service__pb2.ToolChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sf.tools.v1.ToolService/GetSchemas',
            tool__service__pb2.GetSchemasRequest.SerializeToString,
            tool__service__pb2.GetSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
