# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tool_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tool_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tool_service.proto\x12\x0bsf.tools.v1\"r\n\x0bToolContext\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\x12\x14\n\x0cproject_path\x18\x04 \x01(\t\x12\x13\n\x0b\x65pic_run_id\x18\x05 \x01(\t\"a\n\x0bToolRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\x0c\x12%\n\x03\x63tx\x18\x04 \x01(\x0b\x32\x18.sf.tools.v1.ToolContext\"d\n\x0cToolResponse\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06result\x18\x03 \x01(\x0c\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\r\"X\n\tToolChunk\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"<\n\x11GetSchemasRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x15\n\rallowed_tools\x18\x02 \x03(\t\"%\n\x12GetSchemasResponse\x12\x0f\n\x07schemas\x18\x01 \x01(\x0c\x32\xe1\x01\n\x0bToolService\x12>\n\x07\x45xecute\x12\x18.sf.tools.v1.ToolRequest\x1a\x19.sf.tools.v1.ToolResponse\x12\x43\n\rExecuteStream\x12\x18.sf.tools.v1.ToolRequest\x1a\x16.sf.tools.v1.ToolChunk0\x01\x12M\n\nGetSchemas\x12\x1e.sf.tools.v1.GetSchemasRequest\x1a\x1f.sf.tools.v1.GetSchemasResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tool_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLCONTEXT']._serialized_start=35
  _globals['_TOOLCONTEXT']._serialized_end=149
  _globals['_TOOLREQUEST']._serialized_start=151
  _globals['_TOOLREQUEST']._serialized_end=248
  _globals['_TOOLRESPONSE']._serialized_start=250
  _globals['_TOOLRESPONSE']._serialized_end=350
  _globals['_TOOLCHUNK']._serialized_start=352
  _globals['_TOOLCHUNK']._serialized_end=440
  _globals['_GETSCHEMASREQUEST']._serialized_start=442
  _globals['_GETSCHEMASREQUEST']._serialized_end=502
  _globals['_GETSCHEMASRESPONSE']._serialized_start=504
  _globals['_GETSCHEMASRESPONSE']._serialized_end=541
  _globals['_TOOLSERVICE']._serialized_start=544
  _globals['_TOOLSERVICE']._serialized_end=769
# @@protoc_insertion_point(module_scope)
